In [1]:
import requests
from requests.exceptions import RequestException
from contextlib import closing
from bs4 import BeautifulSoup
import pandas as pd
from itertools import cycle
from csv import reader
from pathlib import Path
import seaborn as sns
import numpy as np
import statistics
import ast
import sys
import time
import os
import csv

In [2]:
avg_sector_metrics_df = pd.read_csv(
    Path("Resources/AverageSectorMetrics.csv")
)

avg_sector_metrics_df.columns=['metrics', 'basicmaterials', ' communicationservices', ' consumercyclical',
       ' consumerdefensive', ' energy', ' financial', ' healthcare',
       ' industrials', ' realestate', ' technology', ' utilities']

avg_sector_metrics_df

,metrics,basicmaterials,communicationservices,consumercyclical,consumerdefensive,energy,financial,healthcare,industrials,realestate,technology,utilities
0,Forward PE,11.880,12.680,12.410,15.470,9.300,8.690,18.390,12.910,20.540,17.310,16.125
1,PEG,1.950,2.315,1.520,2.735,0.830,1.060,3.255,1.660,2.550,2.700,3.900
2,Price/Sales,0.760,1.070,0.510,0.880,0.430,2.305,5.760,0.700,2.750,2.230,2.300
3,Price/Book,1.220,1.330,1.150,1.620,0.600,0.780,3.220,1.250,0.990,2.520,1.655
4,Price/FCF,11.940,14.630,10.630,16.710,3.480,8.970,26.175,12.030,24.475,22.660,11.535
5,EPS This Y,-4.400,-0.900,6.300,4.500,-11.800,7.900,9.750,6.900,-0.700,3.300,6.200
6,EPS Next Y,32.800,31.580,50.000,12.605,11.155,8.460,16.900,25.215,9.580,28.425,7.925
7,EPS Next 5Y,8.000,7.850,9.300,7.450,5.050,8.000,12.170,10.000,6.000,14.300,5.250
8,EPS Q/Q,-3.800,-2.400,-1.200,-1.500,-46.000,6.100,12.400,3.900,-2.300,6.500,-2.800
9,Sales Q/Q,-3.000,1.000,1.000,3.600,-8.200,0.900,5.400,0.500,4.300,5.750,-1.900
10,ROA,2.650,1.100,3.700,3.700,-0.100,1.100,-30.000,3.600,1.800,1.200,2.500
11,ROE,5.100,2.800,8.800,8.000,1.100,9.100,-39.900,9.850,4.550,2.800,9.200
12,ROI,6.800,4.000,7.900,7.200,3.550,16.450,-10.100,7.500,2.850,3.050,5.800
13,Current Ratio,2.000,1.400,1.400,1.500,1.100,1.500,3.400,1.800,1.300,1.800,0.800
14,Quick Ratio,1.200,1.300,0.800,0.900,1.000,1.450,3.200,1.300,1.200,1.500,0.600
15,LT Debt/Equity,0.425,0.330,0.490,0.370,0.640,0.150,0.000,0.490,1.010,0.140,1.060
16,Debt/Equity,0.520,0.355,0.590,0.450,0.640,0.150,0.000,0.545,1.070,0.170,1.220
17,Gross Margin,23.000,55.100,32.800,34.000,43.400,73.050,62.000,28.900,63.900,47.100,68.900
18,Operating Margin,7.750,6.200,5.750,5.400,5.450,62.500,5.000,6.800,20.650,3.700,18.600
19,Net Margin,4.200,2.050,3.700,3.400,0.650,21.100,2.500,4.800,12.050,2.000,11.300
20,Perf Month,5.260,1.170,3.820,0.700,8.805,0.690,5.380,-0.505,-6.960,5.565,-5.820
21,Perf Quarter,-28.300,-27.905,-39.710,-15.760,-46.120,-19.850,-15.850,-31.600,-42.085,-18.085,-22.555
22,Perf Half Y,-29.435,-26.110,-39.170,-13.270,-52.310,-16.955,-5.980,-31.900,-39.880,-12.930,-14.795
23,Perf Year,-30.835,-31.980,-39.375,-20.450,-64.140,-13.985,-21.230,-32.820,-41.090,-13.300,-11.615
24,Perf YTD,-32.100,-27.910,-39.780,-18.800,-54.550,-18.400,-14.060,-32.200,-41.630,-15.105,-18.515
25,Volatility Month,5.990,5.620,6.930,4.810,9.910,1.730,8.200,5.770,5.925,5.230,3.680

In [3]:
avg_sector_metrics_df.set_index("metrics", inplace=True, drop=True)

In [4]:
avg_sector_metrics_df.head()

,basicmaterials,communicationservices,consumercyclical,consumerdefensive,energy,financial,healthcare,industrials,realestate,technology,utilities
metrics,,,,,,,,,,,
Forward PE,11.88,12.680,12.41,15.470,9.30,8.690,18.390,12.91,20.540,17.31,16.125
PEG,1.95,2.315,1.52,2.735,0.83,1.060,3.255,1.66,2.550,2.70,3.900
Price/Sales,0.76,1.070,0.51,0.880,0.43,2.305,5.760,0.70,2.750,2.23,2.300
Price/Book,1.22,1.330,1.15,1.620,0.60,0.780,3.220,1.25,0.990,2.52,1.655
Price/FCF,11.94,14.630,10.63,16.710,3.48,8.970,26.175,12.03,24.475,22.66,11.535

In [5]:
val_stats_df = avg_sector_metrics_df.loc[["Forward PE" , "PEG", "Price/Sales", "Price/Book", "Price/FCF"]]

In [6]:
val_stats_df.head()

,basicmaterials,communicationservices,consumercyclical,consumerdefensive,energy,financial,healthcare,industrials,realestate,technology,utilities
metrics,,,,,,,,,,,
Forward PE,11.88,12.680,12.41,15.470,9.30,8.690,18.390,12.91,20.540,17.31,16.125
PEG,1.95,2.315,1.52,2.735,0.83,1.060,3.255,1.66,2.550,2.70,3.900
Price/Sales,0.76,1.070,0.51,0.880,0.43,2.305,5.760,0.70,2.750,2.23,2.300
Price/Book,1.22,1.330,1.15,1.620,0.60,0.780,3.220,1.25,0.990,2.52,1.655
Price/FCF,11.94,14.630,10.63,16.710,3.48,8.970,26.175,12.03,24.475,22.66,11.535

In [7]:
growth_stats_df = avg_sector_metrics_df.loc[["EPS This Y", "EPS Next Y", "EPS Next 5Y", "Sales Q/Q", "EPS Q/Q"]]

In [8]:
growth_stats_df

,basicmaterials,communicationservices,consumercyclical,consumerdefensive,energy,financial,healthcare,industrials,realestate,technology,utilities
metrics,,,,,,,,,,,
EPS This Y,-4.4,-0.90,6.3,4.500,-11.800,7.90,9.75,6.900,-0.70,3.300,6.200
EPS Next Y,32.8,31.58,50.0,12.605,11.155,8.46,16.90,25.215,9.58,28.425,7.925
EPS Next 5Y,8.0,7.85,9.3,7.450,5.050,8.00,12.17,10.000,6.00,14.300,5.250
Sales Q/Q,-3.0,1.00,1.0,3.600,-8.200,0.90,5.40,0.500,4.30,5.750,-1.900
EPS Q/Q,-3.8,-2.40,-1.2,-1.500,-46.000,6.10,12.40,3.900,-2.30,6.500,-2.800

In [9]:
profit_stats_df = avg_sector_metrics_df.loc[["Net Margin", "Operating Margin", "Gross Margin", "ROE", "ROA"]]

In [10]:
profit_stats_df

,basicmaterials,communicationservices,consumercyclical,consumerdefensive,energy,financial,healthcare,industrials,realestate,technology,utilities
metrics,,,,,,,,,,,
Net Margin,4.20,2.05,3.70,3.4,0.65,21.10,2.5,4.80,12.05,2.0,11.3
Operating Margin,7.75,6.20,5.75,5.4,5.45,62.50,5.0,6.80,20.65,3.7,18.6
Gross Margin,23.00,55.10,32.80,34.0,43.40,73.05,62.0,28.90,63.90,47.1,68.9
ROE,5.10,2.80,8.80,8.0,1.10,9.10,-39.9,9.85,4.55,2.8,9.2
ROA,2.65,1.10,3.70,3.7,-0.10,1.10,-30.0,3.60,1.80,1.2,2.5

In [11]:
perf_stats_df = avg_sector_metrics_df.loc[["Perf Month", "Perf Quarter", "Perf Half Y", "Perf Year", "Perf YTD", "Volatility Month"]]

In [12]:
perf_stats_df

,basicmaterials,communicationservices,consumercyclical,consumerdefensive,energy,financial,healthcare,industrials,realestate,technology,utilities
metrics,,,,,,,,,,,
Perf Month,5.260,1.170,3.820,0.70,8.805,0.690,5.38,-0.505,-6.960,5.565,-5.820
Perf Quarter,-28.300,-27.905,-39.710,-15.76,-46.120,-19.850,-15.85,-31.600,-42.085,-18.085,-22.555
Perf Half Y,-29.435,-26.110,-39.170,-13.27,-52.310,-16.955,-5.98,-31.900,-39.880,-12.930,-14.795
Perf Year,-30.835,-31.980,-39.375,-20.45,-64.140,-13.985,-21.23,-32.820,-41.090,-13.300,-11.615
Perf YTD,-32.100,-27.910,-39.780,-18.80,-54.550,-18.400,-14.06,-32.200,-41.630,-15.105,-18.515
Volatility Month,5.990,5.620,6.930,4.81,9.910,1.730,8.20,5.770,5.925,5.230,3.680

In [13]:
daily_returns_perf_df = perf_stats_df.pct_change().dropna()

daily_returns_perf_df

,basicmaterials,communicationservices,consumercyclical,consumerdefensive,energy,financial,healthcare,industrials,realestate,technology,utilities
metrics,,,,,,,,,,,
Perf Quarter,-6.380228,-24.850427,-11.395288,-23.514286,-6.237933,-29.768116,-3.946097,61.574257,5.046695,-4.249775,2.875430
Perf Half Y,0.040106,-0.064325,-0.013599,-0.157995,0.134215,-0.145844,-0.622713,0.009494,-0.052394,-0.285043,-0.344048
Perf Year,0.047562,0.224818,0.005234,0.541070,0.226152,-0.175170,2.550167,0.028840,0.030341,0.028616,-0.214937
Perf YTD,0.041025,-0.127267,0.010286,-0.080685,-0.149517,0.315695,-0.337730,-0.018891,0.013142,0.135714,0.594059
Volatility Month,-1.186604,-1.201362,-1.174208,-1.255851,-1.181668,-1.094022,-1.583215,-1.179193,-1.142325,-1.346243,-1.198758

In [14]:
std_perf_df = daily_returns_perf_df.std()/3

std_perf_df

basicmaterials            0.928794
 communicationservices    3.665397
 consumercyclical         1.663688
 consumerdefensive        3.476464
 energy                   0.912969
 financial                4.399903
 healthcare               0.781369
 industrials              9.223759
 realestate               0.812112
 technology               0.610947
 utilities                0.517381
dtype: float64

In [15]:
daily_returns_growth_df = growth_stats_df.pct_change().dropna()

daily_returns_growth_df

,basicmaterials,communicationservices,consumercyclical,consumerdefensive,energy,financial,healthcare,industrials,realestate,technology,utilities
metrics,,,,,,,,,,,
EPS Next Y,-8.454545,-36.088889,6.936508,1.801111,-1.945339,0.070886,0.733333,2.654348,-14.685714,7.613636,0.278226
EPS Next 5Y,-0.756098,-0.751425,-0.814000,-0.408965,-0.547288,-0.054374,-0.279882,-0.603411,-0.373695,-0.496922,-0.337539
Sales Q/Q,-1.375000,-0.872611,-0.892473,-0.516779,-2.623762,-0.887500,-0.556286,-0.950000,-0.283333,-0.597902,-1.361905
EPS Q/Q,0.266667,-3.400000,-2.200000,-1.416667,4.609756,5.777778,1.296296,6.800000,-1.534884,0.130435,0.473684

In [16]:
std_growth_df = daily_returns_growth_df.std()/3

std_growth_df

basicmaterials            1.324868
 communicationservices    5.750123
 consumercyclical         1.389364
 consumerdefensive        0.455908
 energy                   1.091273
 financial                1.021241
 healthcare               0.288666
 industrials              1.201018
 realestate               2.333591
 technology               1.326870
 utilities                0.275281
dtype: float64

In [17]:
daily_returns_val_df = val_stats_df.pct_change().dropna()

daily_returns_val_df

,basicmaterials,communicationservices,consumercyclical,consumerdefensive,energy,financial,healthcare,industrials,realestate,technology,utilities
metrics,,,,,,,,,,,
PEG,-0.835859,-0.817429,-0.877518,-0.823206,-0.910753,-0.878021,-0.823002,-0.871418,-0.875852,-0.844021,-0.758140
Price/Sales,-0.610256,-0.537797,-0.664474,-0.678245,-0.481928,1.174528,0.769585,-0.578313,0.078431,-0.174074,-0.410256
Price/Book,0.605263,0.242991,1.254902,0.840909,0.395349,-0.661605,-0.440972,0.785714,-0.640000,0.130045,-0.280435
Price/FCF,8.786885,10.000000,8.243478,9.314815,4.800000,10.500000,7.128882,8.624000,23.722222,7.992063,5.969789

In [18]:
std_val_df = daily_returns_val_df.std()/3

std_val_df

basicmaterials            1.525850
 communicationservices    1.734918
 consumercyclical         1.426148
 consumerdefensive        1.608847
 energy                   0.874388
 financial                1.796695
 healthcare               1.236496
 industrials              1.493743
 realestate               4.035828
 technology               1.387990
 utilities                1.077554
dtype: float64

In [19]:
daily_returns_profit_df = profit_stats_df.pct_change().dropna()

daily_returns_profit_df

,basicmaterials,communicationservices,consumercyclical,consumerdefensive,energy,financial,healthcare,industrials,realestate,technology,utilities
metrics,,,,,,,,,,,
Operating Margin,0.845238,2.024390,0.554054,0.588235,7.384615,1.962085,1.000000,0.416667,0.713693,0.850000,0.646018
Gross Margin,1.967742,7.887097,4.704348,5.296296,6.963303,0.168800,11.400000,3.250000,2.094431,11.729730,2.704301
ROE,-0.778261,-0.949183,-0.731707,-0.764706,-0.974654,-0.875428,-1.643548,-0.659170,-0.928795,-0.940552,-0.866473
ROA,-0.480392,-0.607143,-0.579545,-0.537500,-1.090909,-0.879121,-0.248120,-0.634518,-0.604396,-0.571429,-0.728261

In [20]:
std_profit_df = daily_returns_profit_df.std()/3

std_profit_df

basicmaterials            0.422467
 communicationservices    1.362485
 consumercyclical         0.847963
 consumerdefensive        0.943222
 energy                   1.580507
 financial                0.446471
 healthcare               1.982484
 industrials              0.613595
 realestate               0.460177
 technology               2.008283
 utilities                0.552476
dtype: float64

In [60]:
def numeric_to_letter_grade(data):
    
    output = 'F'
    data = std_profit_df["basicmaterials"]
    
    if data == 4.3:
        output = 'A+'
    elif data >= 4.0:
        data = 'A'
    elif data >= 3.7:
        output = 'A-'
    elif data >= 3.3:
        output = 'B+'
    elif data >= 3:
        output = 'B'
    elif data >= 2.7:
        output = 'B-'
    elif data >= 2.3:
        output = 'C+'
    elif data >= 2:
        output = 'C'
    elif data >= 1.7:
        output = 'C-'
    elif data >= 1.3:
        output = 'D+'
    elif data >= 1:
        output = 'D'
    elif data >= 0.7:
        output = 'D-'

    return output

In [61]:
data = std_profit_df["basicmaterials"]

numeric_to_letter_grade(data)
   # return output.apply(numeric_to_letter_grade)

'F'

In [55]:
def numeric_to_letter_grade(data):
    
    output = 'F'
    data = std_profit_df[" energy"]
    
    if data == 4.3:
        output = 'A+'
    elif data >= 4.0:
        data = 'A'
    elif data >= 3.7:
        output = 'A-'
    elif data >= 3.3:
        output = 'B+'
    elif data >= 3:
        output = 'B'
    elif data >= 2.7:
        output = 'B-'
    elif data >= 2.3:
        output = 'C+'
    elif data >= 2:
        output = 'C'
    elif data >= 1.7:
        output = 'C-'
    elif data >= 1.3:
        output = 'D+'
    elif data >= 1:
        output = 'D'
    elif data >= 0.7:
        output = 'D-'

    return output

In [56]:
data = std_profit_df[" energy"]
output = "A"

numeric_to_letter_grade(data)
   # return output.apply(numeric_to_letter_grade)

'D+'

In [83]:
def numeric_to_letter_grade(data):
    
    output = 'F'
    data = std_profit_df[" consumercyclical"]
    
    if data == 4.3:
        output = 'A+'
    elif data >= 4.0:
        data = 'A'
    elif data >= 3.7:
        output = 'A-'
    elif data >= 3.3:
        output = 'B+'
    elif data >= 3:
        output = 'B'
    elif data >= 2.7:
        output = 'B-'
    elif data >= 2.3:
        output = 'C+'
    elif data >= 2:
        output = 'C'
    elif data >= 1.7:
        output = 'C-'
    elif data >= 1.3:
        output = 'D+'
    elif data >= 1:
        output = 'D'
    elif data >= 0.7:
        output = 'D-'

    return output

In [84]:
data = std_profit_df[" consumercyclical"]
output = "A"

numeric_to_letter_grade(data)
   # return output.apply(numeric_to_letter_grade)

'D-'

In [64]:
def numeric_to_letter_grade(data):
    
    output = 'F'
    data = std_profit_df[" consumerdefensive"]
    
    if data == 4.3:
        output = 'A+'
    elif data >= 4.0:
        data = 'A'
    elif data >= 3.7:
        output = 'A-'
    elif data >= 3.3:
        output = 'B+'
    elif data >= 3:
        output = 'B'
    elif data >= 2.7:
        output = 'B-'
    elif data >= 2.3:
        output = 'C+'
    elif data >= 2:
        output = 'C'
    elif data >= 1.7:
        output = 'C-'
    elif data >= 1.3:
        output = 'D+'
    elif data >= 1:
        output = 'D'
    elif data >= 0.7:
        output = 'D-'

    return output

In [65]:
data = std_profit_df[" consumerdefensive"]
output = "A"

numeric_to_letter_grade(data)
   # return output.apply(numeric_to_letter_grade)

'D-'

In [66]:
def numeric_to_letter_grade(data):
    
    output = 'F'
    data = std_profit_df[" energy"]
    
    if data == 4.3:
        output = 'A+'
    elif data >= 4.0:
        data = 'A'
    elif data >= 3.7:
        output = 'A-'
    elif data >= 3.3:
        output = 'B+'
    elif data >= 3:
        output = 'B'
    elif data >= 2.7:
        output = 'B-'
    elif data >= 2.3:
        output = 'C+'
    elif data >= 2:
        output = 'C'
    elif data >= 1.7:
        output = 'C-'
    elif data >= 1.3:
        output = 'D+'
    elif data >= 1:
        output = 'D'
    elif data >= 0.7:
        output = 'D-'

    return output

In [67]:
data = std_profit_df[" energy"]
output = "A"

numeric_to_letter_grade(data)
   # return output.apply(numeric_to_letter_grade)

'D+'

In [68]:
def numeric_to_letter_grade(data):
    
    output = 'F'
    data = std_profit_df[" financial"]
    
    if data == 4.3:
        output = 'A+'
    elif data >= 4.0:
        data = 'A'
    elif data >= 3.7:
        output = 'A-'
    elif data >= 3.3:
        output = 'B+'
    elif data >= 3:
        output = 'B'
    elif data >= 2.7:
        output = 'B-'
    elif data >= 2.3:
        output = 'C+'
    elif data >= 2:
        output = 'C'
    elif data >= 1.7:
        output = 'C-'
    elif data >= 1.3:
        output = 'D+'
    elif data >= 1:
        output = 'D'
    elif data >= 0.7:
        output = 'D-'

    return output

In [69]:
data = std_profit_df[" financial"]
output = "A"

numeric_to_letter_grade(data)
   # return output.apply(numeric_to_letter_grade)

'F'

In [70]:
def numeric_to_letter_grade(data):
    
    output = 'F'
    data = std_profit_df[" healthcare"]
    
    if data == 4.3:
        output = 'A+'
    elif data >= 4.0:
        data = 'A'
    elif data >= 3.7:
        output = 'A-'
    elif data >= 3.3:
        output = 'B+'
    elif data >= 3:
        output = 'B'
    elif data >= 2.7:
        output = 'B-'
    elif data >= 2.3:
        output = 'C+'
    elif data >= 2:
        output = 'C'
    elif data >= 1.7:
        output = 'C-'
    elif data >= 1.3:
        output = 'D+'
    elif data >= 1:
        output = 'D'
    elif data >= 0.7:
        output = 'D-'

    return output

In [71]:
data = std_profit_df[" healthcare"]
output = "A"

numeric_to_letter_grade(data)
   # return output.apply(numeric_to_letter_grade)

'C-'

In [72]:
def numeric_to_letter_grade(data):
    
    output = 'F'
    data = std_profit_df[" industrials"]
    
    if data == 4.3:
        output = 'A+'
    elif data >= 4.0:
        data = 'A'
    elif data >= 3.7:
        output = 'A-'
    elif data >= 3.3:
        output = 'B+'
    elif data >= 3:
        output = 'B'
    elif data >= 2.7:
        output = 'B-'
    elif data >= 2.3:
        output = 'C+'
    elif data >= 2:
        output = 'C'
    elif data >= 1.7:
        output = 'C-'
    elif data >= 1.3:
        output = 'D+'
    elif data >= 1:
        output = 'D'
    elif data >= 0.7:
        output = 'D-'

    return output

In [73]:
data = std_profit_df[" industrials"]
output = "A"

numeric_to_letter_grade(data)
   # return output.apply(numeric_to_letter_grade)

'F'

In [ ]:
def numeric_to_letter_grade(data):
    
    output = 'F'
    data = std_profit_df[" realestate"]
    
    if data == 4.3:
        output = 'A+'
    elif data >= 4.0:
        data = 'A'
    elif data >= 3.7:
        output = 'A-'
    elif data >= 3.3:
        output = 'B+'
    elif data >= 3:
        output = 'B'
    elif data >= 2.7:
        output = 'B-'
    elif data >= 2.3:
        output = 'C+'
    elif data >= 2:
        output = 'C'
    elif data >= 1.7:
        output = 'C-'
    elif data >= 1.3:
        output = 'D+'
    elif data >= 1:
        output = 'D'
    elif data >= 0.7:
        output = 'D-'

    return output

In [74]:
data = std_profit_df[" realestate"]
output = "A"

numeric_to_letter_grade(data)
   # return output.apply(numeric_to_letter_grade)

'F'

In [75]:
def numeric_to_letter_grade(data):
    
    output = 'F'
    data = std_profit_df[" technology"]
    
    if data == 4.3:
        output = 'A+'
    elif data >= 4.0:
        data = 'A'
    elif data >= 3.7:
        output = 'A-'
    elif data >= 3.3:
        output = 'B+'
    elif data >= 3:
        output = 'B'
    elif data >= 2.7:
        output = 'B-'
    elif data >= 2.3:
        output = 'C+'
    elif data >= 2:
        output = 'C'
    elif data >= 1.7:
        output = 'C-'
    elif data >= 1.3:
        output = 'D+'
    elif data >= 1:
        output = 'D'
    elif data >= 0.7:
        output = 'D-'

    return output

In [76]:
data = std_profit_df[" technology"]
output = "A"

numeric_to_letter_grade(data)
   # return output.apply(numeric_to_letter_grade)

'C'

In [77]:
def numeric_to_letter_grade(data):
    
    output = 'F'
    data = std_profit_df[" utilities"]
    
    if data == 4.3:
        output = 'A+'
    elif data >= 4.0:
        data = 'A'
    elif data >= 3.7:
        output = 'A-'
    elif data >= 3.3:
        output = 'B+'
    elif data >= 3:
        output = 'B'
    elif data >= 2.7:
        output = 'B-'
    elif data >= 2.3:
        output = 'C+'
    elif data >= 2:
        output = 'C'
    elif data >= 1.7:
        output = 'C-'
    elif data >= 1.3:
        output = 'D+'
    elif data >= 1:
        output = 'D'
    elif data >= 0.7:
        output = 'D-'

    return output

In [78]:
data = std_profit_df[" utilities"]
output = "A"

numeric_to_letter_grade(data)
   # return output.apply(numeric_to_letter_grade)

'F'

In [85]:
def numeric_to_letter_grade(data):
    
    output = 'F'
    data = std_val_df["basicmaterials"]
    
    if data == 4.3:
        output = 'A+'
    elif data >= 4.0:
        data = 'A'
    elif data >= 3.7:
        output = 'A-'
    elif data >= 3.3:
        output = 'B+'
    elif data >= 3:
        output = 'B'
    elif data >= 2.7:
        output = 'B-'
    elif data >= 2.3:
        output = 'C+'
    elif data >= 2:
        output = 'C'
    elif data >= 1.7:
        output = 'C-'
    elif data >= 1.3:
        output = 'D+'
    elif data >= 1:
        output = 'D'
    elif data >= 0.7:
        output = 'D-'

    return output

In [86]:
data = std_val_df["basicmaterials"]
output = "A"

numeric_to_letter_grade(data)
   # return output.apply(numeric_to_letter_grade)

'D+'

In [87]:
def numeric_to_letter_grade(data):
    
    output = 'F'
    data = std_val_df[" communicationservices"]
    
    if data == 4.3:
        output = 'A+'
    elif data >= 4.0:
        data = 'A'
    elif data >= 3.7:
        output = 'A-'
    elif data >= 3.3:
        output = 'B+'
    elif data >= 3:
        output = 'B'
    elif data >= 2.7:
        output = 'B-'
    elif data >= 2.3:
        output = 'C+'
    elif data >= 2:
        output = 'C'
    elif data >= 1.7:
        output = 'C-'
    elif data >= 1.3:
        output = 'D+'
    elif data >= 1:
        output = 'D'
    elif data >= 0.7:
        output = 'D-'

    return output

In [88]:
data = std_val_df[" communicationservices"]
output = "A"

numeric_to_letter_grade(data)
   # return output.apply(numeric_to_letter_grade)

'C-'

In [89]:
def numeric_to_letter_grade(data):
    
    output = 'F'
    data = std_val_df[" consumercyclical"]
    
    if data == 4.3:
        output = 'A+'
    elif data >= 4.0:
        data = 'A'
    elif data >= 3.7:
        output = 'A-'
    elif data >= 3.3:
        output = 'B+'
    elif data >= 3:
        output = 'B'
    elif data >= 2.7:
        output = 'B-'
    elif data >= 2.3:
        output = 'C+'
    elif data >= 2:
        output = 'C'
    elif data >= 1.7:
        output = 'C-'
    elif data >= 1.3:
        output = 'D+'
    elif data >= 1:
        output = 'D'
    elif data >= 0.7:
        output = 'D-'

    return output

In [90]:
data = std_val_df[" consumercyclical"]
output = "A"

numeric_to_letter_grade(data)
   # return output.apply(numeric_to_letter_grade)

'D+'

In [91]:
def numeric_to_letter_grade(data):
    
    output = 'F'
    data = std_val_df[" consumerdefensive"]
    
    if data == 4.3:
        output = 'A+'
    elif data >= 4.0:
        data = 'A'
    elif data >= 3.7:
        output = 'A-'
    elif data >= 3.3:
        output = 'B+'
    elif data >= 3:
        output = 'B'
    elif data >= 2.7:
        output = 'B-'
    elif data >= 2.3:
        output = 'C+'
    elif data >= 2:
        output = 'C'
    elif data >= 1.7:
        output = 'C-'
    elif data >= 1.3:
        output = 'D+'
    elif data >= 1:
        output = 'D'
    elif data >= 0.7:
        output = 'D-'

    return output

In [92]:
data = std_val_df[" consumerdefensive"]
output = "A"

numeric_to_letter_grade(data)
   # return output.apply(numeric_to_letter_grade)

'D+'

In [93]:
def numeric_to_letter_grade(data):
    
    output = 'F'
    data = std_val_df[" energy"]
    
    if data == 4.3:
        output = 'A+'
    elif data >= 4.0:
        data = 'A'
    elif data >= 3.7:
        output = 'A-'
    elif data >= 3.3:
        output = 'B+'
    elif data >= 3:
        output = 'B'
    elif data >= 2.7:
        output = 'B-'
    elif data >= 2.3:
        output = 'C+'
    elif data >= 2:
        output = 'C'
    elif data >= 1.7:
        output = 'C-'
    elif data >= 1.3:
        output = 'D+'
    elif data >= 1:
        output = 'D'
    elif data >= 0.7:
        output = 'D-'

    return output

In [95]:
data = std_val_df[" energy"]
output = "A"

numeric_to_letter_grade(data)
   # return output.apply(numeric_to_letter_grade)

'D-'

In [96]:
def numeric_to_letter_grade(data):
    
    output = 'F'
    data = std_val_df[" financial"]
    
    if data == 4.3:
        output = 'A+'
    elif data >= 4.0:
        data = 'A'
    elif data >= 3.7:
        output = 'A-'
    elif data >= 3.3:
        output = 'B+'
    elif data >= 3:
        output = 'B'
    elif data >= 2.7:
        output = 'B-'
    elif data >= 2.3:
        output = 'C+'
    elif data >= 2:
        output = 'C'
    elif data >= 1.7:
        output = 'C-'
    elif data >= 1.3:
        output = 'D+'
    elif data >= 1:
        output = 'D'
    elif data >= 0.7:
        output = 'D-'

    return output

In [97]:
data = std_val_df[" financial"]
output = "A"

numeric_to_letter_grade(data)
   # return output.apply(numeric_to_letter_grade)

'C-'

In [98]:
def numeric_to_letter_grade(data):
    
    output = 'F'
    data = std_val_df[" healthcare"]
    
    if data == 4.3:
        output = 'A+'
    elif data >= 4.0:
        data = 'A'
    elif data >= 3.7:
        output = 'A-'
    elif data >= 3.3:
        output = 'B+'
    elif data >= 3:
        output = 'B'
    elif data >= 2.7:
        output = 'B-'
    elif data >= 2.3:
        output = 'C+'
    elif data >= 2:
        output = 'C'
    elif data >= 1.7:
        output = 'C-'
    elif data >= 1.3:
        output = 'D+'
    elif data >= 1:
        output = 'D'
    elif data >= 0.7:
        output = 'D-'

    return output

In [99]:
data = std_val_df[" healthcare"]
output = "A"

numeric_to_letter_grade(data)
   # return output.apply(numeric_to_letter_grade)

'D'

In [100]:
def numeric_to_letter_grade(data):
    
    output = 'F'
    data = std_val_df[" industrials"]
    
    if data == 4.3:
        output = 'A+'
    elif data >= 4.0:
        data = 'A'
    elif data >= 3.7:
        output = 'A-'
    elif data >= 3.3:
        output = 'B+'
    elif data >= 3:
        output = 'B'
    elif data >= 2.7:
        output = 'B-'
    elif data >= 2.3:
        output = 'C+'
    elif data >= 2:
        output = 'C'
    elif data >= 1.7:
        output = 'C-'
    elif data >= 1.3:
        output = 'D+'
    elif data >= 1:
        output = 'D'
    elif data >= 0.7:
        output = 'D-'

    return output

In [101]:
data = std_val_df[" industrials"]
output = "A"

numeric_to_letter_grade(data)
   # return output.apply(numeric_to_letter_grade)

'D+'

In [102]:
def numeric_to_letter_grade(data):
    
    output = 'F'
    data = std_val_df[" realestate"]
    
    if data == 4.3:
        output = 'A+'
    elif data >= 4.0:
        data = 'A'
    elif data >= 3.7:
        output = 'A-'
    elif data >= 3.3:
        output = 'B+'
    elif data >= 3:
        output = 'B'
    elif data >= 2.7:
        output = 'B-'
    elif data >= 2.3:
        output = 'C+'
    elif data >= 2:
        output = 'C'
    elif data >= 1.7:
        output = 'C-'
    elif data >= 1.3:
        output = 'D+'
    elif data >= 1:
        output = 'D'
    elif data >= 0.7:
        output = 'D-'

    return output

In [103]:
data = std_val_df[" realestate"]
output = "A"

numeric_to_letter_grade(data)
   # return output.apply(numeric_to_letter_grade)

'F'

In [104]:
def numeric_to_letter_grade(data):
    
    output = 'F'
    data = std_val_df[" technology"]
    
    if data == 4.3:
        output = 'A+'
    elif data >= 4.0:
        data = 'A'
    elif data >= 3.7:
        output = 'A-'
    elif data >= 3.3:
        output = 'B+'
    elif data >= 3:
        output = 'B'
    elif data >= 2.7:
        output = 'B-'
    elif data >= 2.3:
        output = 'C+'
    elif data >= 2:
        output = 'C'
    elif data >= 1.7:
        output = 'C-'
    elif data >= 1.3:
        output = 'D+'
    elif data >= 1:
        output = 'D'
    elif data >= 0.7:
        output = 'D-'

    return output

In [105]:
data = std_val_df[" technology"]
output = "A"

numeric_to_letter_grade(data)
   # return output.apply(numeric_to_letter_grade)

'D+'

In [106]:
def numeric_to_letter_grade(data):
    
    output = 'F'
    data = std_val_df[" utilities"]
    
    if data == 4.3:
        output = 'A+'
    elif data >= 4.0:
        data = 'A'
    elif data >= 3.7:
        output = 'A-'
    elif data >= 3.3:
        output = 'B+'
    elif data >= 3:
        output = 'B'
    elif data >= 2.7:
        output = 'B-'
    elif data >= 2.3:
        output = 'C+'
    elif data >= 2:
        output = 'C'
    elif data >= 1.7:
        output = 'C-'
    elif data >= 1.3:
        output = 'D+'
    elif data >= 1:
        output = 'D'
    elif data >= 0.7:
        output = 'D-'

    return output

In [107]:
data = std_val_df[" utilities"]
output = "A"

numeric_to_letter_grade(data)
   # return output.apply(numeric_to_letter_grade)

'D'

In [112]:
def numeric_to_letter_grade(data):
    
    output = 'F'
    data = std_growth_df["basicmaterials"]
    
    if data == 4.3:
        output = 'A+'
    elif data >= 4.0:
        data = 'A'
    elif data >= 3.7:
        output = 'A-'
    elif data >= 3.3:
        output = 'B+'
    elif data >= 3:
        output = 'B'
    elif data >= 2.7:
        output = 'B-'
    elif data >= 2.3:
        output = 'C+'
    elif data >= 2:
        output = 'C'
    elif data >= 1.7:
        output = 'C-'
    elif data >= 1.3:
        output = 'D+'
    elif data >= 1:
        output = 'D'
    elif data >= 0.7:
        output = 'D-'

    return output

In [113]:
data = std_growth_df["basicmaterials"]
output = "A"

numeric_to_letter_grade(data)
   # return output.apply(numeric_to_letter_grade)

'D+'

In [114]:
def numeric_to_letter_grade(data):
    
    output = 'F'
    data = std_growth_df[" communicationservices"]
    
    if data == 4.3:
        output = 'A+'
    elif data >= 4.0:
        data = 'A'
    elif data >= 3.7:
        output = 'A-'
    elif data >= 3.3:
        output = 'B+'
    elif data >= 3:
        output = 'B'
    elif data >= 2.7:
        output = 'B-'
    elif data >= 2.3:
        output = 'C+'
    elif data >= 2:
        output = 'C'
    elif data >= 1.7:
        output = 'C-'
    elif data >= 1.3:
        output = 'D+'
    elif data >= 1:
        output = 'D'
    elif data >= 0.7:
        output = 'D-'

    return output

In [118]:
data = std_growth_df[" communicationservices"]
output = "A"

numeric_to_letter_grade(data)
   # return output.apply(numeric_to_letter_grade)

'D+'

In [117]:
def numeric_to_letter_grade(data):
    
    output = 'F'
    data = std_growth_df[" consumercyclical"]
    
    if data == 4.3:
        output = 'A+'
    elif data >= 4.0:
        data = 'A'
    elif data >= 3.7:
        output = 'A-'
    elif data >= 3.3:
        output = 'B+'
    elif data >= 3:
        output = 'B'
    elif data >= 2.7:
        output = 'B-'
    elif data >= 2.3:
        output = 'C+'
    elif data >= 2:
        output = 'C'
    elif data >= 1.7:
        output = 'C-'
    elif data >= 1.3:
        output = 'D+'
    elif data >= 1:
        output = 'D'
    elif data >= 0.7:
        output = 'D-'

    return output

In [119]:
data = std_growth_df[" consumercyclical"]
output = "A"

numeric_to_letter_grade(data)
   # return output.apply(numeric_to_letter_grade)

'D+'

In [120]:
def numeric_to_letter_grade(data):
    
    output = 'F'
    data = std_growth_df[" consumerdefensive"]
    
    if data == 4.3:
        output = 'A+'
    elif data >= 4.0:
        data = 'A'
    elif data >= 3.7:
        output = 'A-'
    elif data >= 3.3:
        output = 'B+'
    elif data >= 3:
        output = 'B'
    elif data >= 2.7:
        output = 'B-'
    elif data >= 2.3:
        output = 'C+'
    elif data >= 2:
        output = 'C'
    elif data >= 1.7:
        output = 'C-'
    elif data >= 1.3:
        output = 'D+'
    elif data >= 1:
        output = 'D'
    elif data >= 0.7:
        output = 'D-'

    return output

In [121]:
data = std_val_df[" consumerdefensive"]
output = "A"

numeric_to_letter_grade(data)
   # return output.apply(numeric_to_letter_grade)

'F'

In [123]:
def numeric_to_letter_grade(data):
    
    output = 'F'
    data = std_growth_df[" energy"]
    
    if data == 4.3:
        output = 'A+'
    elif data >= 4.0:
        data = 'A'
    elif data >= 3.7:
        output = 'A-'
    elif data >= 3.3:
        output = 'B+'
    elif data >= 3:
        output = 'B'
    elif data >= 2.7:
        output = 'B-'
    elif data >= 2.3:
        output = 'C+'
    elif data >= 2:
        output = 'C'
    elif data >= 1.7:
        output = 'C-'
    elif data >= 1.3:
        output = 'D+'
    elif data >= 1:
        output = 'D'
    elif data >= 0.7:
        output = 'D-'

    return output

In [124]:
data = std_growth_df[" energy"]
output = "A"

numeric_to_letter_grade(data)
   # return output.apply(numeric_to_letter_grade)

'D'

In [125]:
def numeric_to_letter_grade(data):
    
    output = 'F'
    data = std_growth_df[" financial"]
    
    if data == 4.3:
        output = 'A+'
    elif data >= 4.0:
        data = 'A'
    elif data >= 3.7:
        output = 'A-'
    elif data >= 3.3:
        output = 'B+'
    elif data >= 3:
        output = 'B'
    elif data >= 2.7:
        output = 'B-'
    elif data >= 2.3:
        output = 'C+'
    elif data >= 2:
        output = 'C'
    elif data >= 1.7:
        output = 'C-'
    elif data >= 1.3:
        output = 'D+'
    elif data >= 1:
        output = 'D'
    elif data >= 0.7:
        output = 'D-'

    return output

In [126]:
data = std_growth_df[" financial"]
output = "A"

numeric_to_letter_grade(data)
   # return output.apply(numeric_to_letter_grade)

'D'

In [127]:
def numeric_to_letter_grade(data):
    
    output = 'F'
    data = std_growth_df[" healthcare"]
    
    if data == 4.3:
        output = 'A+'
    elif data >= 4.0:
        data = 'A'
    elif data >= 3.7:
        output = 'A-'
    elif data >= 3.3:
        output = 'B+'
    elif data >= 3:
        output = 'B'
    elif data >= 2.7:
        output = 'B-'
    elif data >= 2.3:
        output = 'C+'
    elif data >= 2:
        output = 'C'
    elif data >= 1.7:
        output = 'C-'
    elif data >= 1.3:
        output = 'D+'
    elif data >= 1:
        output = 'D'
    elif data >= 0.7:
        output = 'D-'

    return output

In [128]:
data = std_growth_df[" healthcare"]
output = "A"

numeric_to_letter_grade(data)
   # return output.apply(numeric_to_letter_grade)

'F'

In [129]:
def numeric_to_letter_grade(data):
    
    output = 'F'
    data = std_growth_df[" industrials"]
    
    if data == 4.3:
        output = 'A+'
    elif data >= 4.0:
        data = 'A'
    elif data >= 3.7:
        output = 'A-'
    elif data >= 3.3:
        output = 'B+'
    elif data >= 3:
        output = 'B'
    elif data >= 2.7:
        output = 'B-'
    elif data >= 2.3:
        output = 'C+'
    elif data >= 2:
        output = 'C'
    elif data >= 1.7:
        output = 'C-'
    elif data >= 1.3:
        output = 'D+'
    elif data >= 1:
        output = 'D'
    elif data >= 0.7:
        output = 'D-'

    return output

In [130]:
data = std_growth_df[" industrials"]
output = "A"

numeric_to_letter_grade(data)
   # return output.apply(numeric_to_letter_grade)

'D'

In [131]:
def numeric_to_letter_grade(data):
    
    output = 'F'
    data = std_growth_df[" realestate"]
    
    if data == 4.3:
        output = 'A+'
    elif data >= 4.0:
        data = 'A'
    elif data >= 3.7:
        output = 'A-'
    elif data >= 3.3:
        output = 'B+'
    elif data >= 3:
        output = 'B'
    elif data >= 2.7:
        output = 'B-'
    elif data >= 2.3:
        output = 'C+'
    elif data >= 2:
        output = 'C'
    elif data >= 1.7:
        output = 'C-'
    elif data >= 1.3:
        output = 'D+'
    elif data >= 1:
        output = 'D'
    elif data >= 0.7:
        output = 'D-'

    return output

In [132]:
data = std_growth_df[" realestate"]
output = "A"

numeric_to_letter_grade(data)
   # return output.apply(numeric_to_letter_grade)

'C+'

In [133]:
def numeric_to_letter_grade(data):
    
    output = 'F'
    data = std_growth_df[" technology"]
    
    if data == 4.3:
        output = 'A+'
    elif data >= 4.0:
        data = 'A'
    elif data >= 3.7:
        output = 'A-'
    elif data >= 3.3:
        output = 'B+'
    elif data >= 3:
        output = 'B'
    elif data >= 2.7:
        output = 'B-'
    elif data >= 2.3:
        output = 'C+'
    elif data >= 2:
        output = 'C'
    elif data >= 1.7:
        output = 'C-'
    elif data >= 1.3:
        output = 'D+'
    elif data >= 1:
        output = 'D'
    elif data >= 0.7:
        output = 'D-'

    return output

In [135]:
data = std_growth_df[" technology"]
output = "A"

numeric_to_letter_grade(data)
   # return output.apply(numeric_to_letter_grade)

'D+'

In [136]:
def numeric_to_letter_grade(data):
    
    output = 'F'
    data = std_growth_df[" utilities"]
    
    if data == 4.3:
        output = 'A+'
    elif data >= 4.0:
        data = 'A'
    elif data >= 3.7:
        output = 'A-'
    elif data >= 3.3:
        output = 'B+'
    elif data >= 3:
        output = 'B'
    elif data >= 2.7:
        output = 'B-'
    elif data >= 2.3:
        output = 'C+'
    elif data >= 2:
        output = 'C'
    elif data >= 1.7:
        output = 'C-'
    elif data >= 1.3:
        output = 'D+'
    elif data >= 1:
        output = 'D'
    elif data >= 0.7:
        output = 'D-'

    return output

In [137]:
data = std_growth_df[" utilities"]
output = "A"

numeric_to_letter_grade(data)
   # return output.apply(numeric_to_letter_grade)

'F'

In [138]:
def numeric_to_letter_grade(data):
    
    output = 'F'
    data = std_perf_df["basicmaterials"]
    
    if data == 4.3:
        output = 'A+'
    elif data >= 4.0:
        data = 'A'
    elif data >= 3.7:
        output = 'A-'
    elif data >= 3.3:
        output = 'B+'
    elif data >= 3:
        output = 'B'
    elif data >= 2.7:
        output = 'B-'
    elif data >= 2.3:
        output = 'C+'
    elif data >= 2:
        output = 'C'
    elif data >= 1.7:
        output = 'C-'
    elif data >= 1.3:
        output = 'D+'
    elif data >= 1:
        output = 'D'
    elif data >= 0.7:
        output = 'D-'

    return output

In [140]:
data = std_perf_df["basicmaterials"]
output = "A"

numeric_to_letter_grade(data)
   # return output.apply(numeric_to_letter_grade)

'D-'

In [141]:
def numeric_to_letter_grade(data):
    
    output = 'F'
    data = std_perf_df[" communicationservices"]
    
    if data == 4.3:
        output = 'A+'
    elif data >= 4.0:
        data = 'A'
    elif data >= 3.7:
        output = 'A-'
    elif data >= 3.3:
        output = 'B+'
    elif data >= 3:
        output = 'B'
    elif data >= 2.7:
        output = 'B-'
    elif data >= 2.3:
        output = 'C+'
    elif data >= 2:
        output = 'C'
    elif data >= 1.7:
        output = 'C-'
    elif data >= 1.3:
        output = 'D+'
    elif data >= 1:
        output = 'D'
    elif data >= 0.7:
        output = 'D-'

    return output

In [142]:
data = std_perf_df[" communicationservices"]
output = "A"

numeric_to_letter_grade(data)
   # return output.apply(numeric_to_letter_grade)

'B+'

In [143]:
def numeric_to_letter_grade(data):
    
    output = 'F'
    data = std_perf_df[" consumercyclical"]
    
    if data == 4.3:
        output = 'A+'
    elif data >= 4.0:
        data = 'A'
    elif data >= 3.7:
        output = 'A-'
    elif data >= 3.3:
        output = 'B+'
    elif data >= 3:
        output = 'B'
    elif data >= 2.7:
        output = 'B-'
    elif data >= 2.3:
        output = 'C+'
    elif data >= 2:
        output = 'C'
    elif data >= 1.7:
        output = 'C-'
    elif data >= 1.3:
        output = 'D+'
    elif data >= 1:
        output = 'D'
    elif data >= 0.7:
        output = 'D-'

    return output

In [144]:
data = std_perf_df[" consumercyclical"]
output = "A"

numeric_to_letter_grade(data)
   # return output.apply(numeric_to_letter_grade)

'D+'

In [145]:
def numeric_to_letter_grade(data):
    
    output = 'F'
    data = std_perf_df[" consumerdefensive"]
    
    if data == 4.3:
        output = 'A+'
    elif data >= 4.0:
        data = 'A'
    elif data >= 3.7:
        output = 'A-'
    elif data >= 3.3:
        output = 'B+'
    elif data >= 3:
        output = 'B'
    elif data >= 2.7:
        output = 'B-'
    elif data >= 2.3:
        output = 'C+'
    elif data >= 2:
        output = 'C'
    elif data >= 1.7:
        output = 'C-'
    elif data >= 1.3:
        output = 'D+'
    elif data >= 1:
        output = 'D'
    elif data >= 0.7:
        output = 'D-'

    return output

In [146]:
data = std_perf_df[" consumerdefensive"]
output = "A"

numeric_to_letter_grade(data)
   # return output.apply(numeric_to_letter_grade)

'B+'

In [147]:
def numeric_to_letter_grade(data):
    
    output = 'F'
    data = std_perf_df[" energy"]
    
    if data == 4.3:
        output = 'A+'
    elif data >= 4.0:
        data = 'A'
    elif data >= 3.7:
        output = 'A-'
    elif data >= 3.3:
        output = 'B+'
    elif data >= 3:
        output = 'B'
    elif data >= 2.7:
        output = 'B-'
    elif data >= 2.3:
        output = 'C+'
    elif data >= 2:
        output = 'C'
    elif data >= 1.7:
        output = 'C-'
    elif data >= 1.3:
        output = 'D+'
    elif data >= 1:
        output = 'D'
    elif data >= 0.7:
        output = 'D-'

    return output

In [148]:
data = std_perf_df[" energy"]
output = "A"

numeric_to_letter_grade(data)
   # return output.apply(numeric_to_letter_grade)

'D-'

In [149]:
def numeric_to_letter_grade(data):
    
    output = 'F'
    data = std_perf_df[" financial"]
    
    if data == 4.3:
        output = 'A+'
    elif data >= 4.0:
        data = 'A'
    elif data >= 3.7:
        output = 'A-'
    elif data >= 3.3:
        output = 'B+'
    elif data >= 3:
        output = 'B'
    elif data >= 2.7:
        output = 'B-'
    elif data >= 2.3:
        output = 'C+'
    elif data >= 2:
        output = 'C'
    elif data >= 1.7:
        output = 'C-'
    elif data >= 1.3:
        output = 'D+'
    elif data >= 1:
        output = 'D'
    elif data >= 0.7:
        output = 'D-'

    return output

In [150]:
data = std_perf_df[" financial"]
output = "A"

numeric_to_letter_grade(data)
   # return output.apply(numeric_to_letter_grade)

'F'

In [151]:
def numeric_to_letter_grade(data):
    
    output = 'F'
    data = std_perf_df[" healthcare"]
    
    if data == 4.3:
        output = 'A+'
    elif data >= 4.0:
        data = 'A'
    elif data >= 3.7:
        output = 'A-'
    elif data >= 3.3:
        output = 'B+'
    elif data >= 3:
        output = 'B'
    elif data >= 2.7:
        output = 'B-'
    elif data >= 2.3:
        output = 'C+'
    elif data >= 2:
        output = 'C'
    elif data >= 1.7:
        output = 'C-'
    elif data >= 1.3:
        output = 'D+'
    elif data >= 1:
        output = 'D'
    elif data >= 0.7:
        output = 'D-'

    return output

In [152]:
data = std_perf_df[" healthcare"]
output = "A"

numeric_to_letter_grade(data)
   # return output.apply(numeric_to_letter_grade)

'D-'

In [156]:
def numeric_to_letter_grade(data):
    
    output = 'F'
    data = std_perf_df[" industrials"]
    
    if data == 4.3:
        output = 'A+'
    elif data >= 4.0:
        data = 'A'
    elif data >= 3.7:
        output = 'A-'
    elif data >= 3.3:
        output = 'B+'
    elif data >= 3:
        output = 'B'
    elif data >= 2.7:
        output = 'B-'
    elif data >= 2.3:
        output = 'C+'
    elif data >= 2:
        output = 'C'
    elif data >= 1.7:
        output = 'C-'
    elif data >= 1.3:
        output = 'D+'
    elif data >= 1:
        output = 'D'
    elif data >= 0.7:
        output = 'D-'

    return output

In [157]:
data = std_perf_df[" industrials"]
output = "A"

numeric_to_letter_grade(data)
   # return output.apply(numeric_to_letter_grade)

'F'

In [158]:
def numeric_to_letter_grade(data):
    
    output = 'F'
    data = std_perf_df[" realestate"]
    
    if data == 4.3:
        output = 'A+'
    elif data >= 4.0:
        data = 'A'
    elif data >= 3.7:
        output = 'A-'
    elif data >= 3.3:
        output = 'B+'
    elif data >= 3:
        output = 'B'
    elif data >= 2.7:
        output = 'B-'
    elif data >= 2.3:
        output = 'C+'
    elif data >= 2:
        output = 'C'
    elif data >= 1.7:
        output = 'C-'
    elif data >= 1.3:
        output = 'D+'
    elif data >= 1:
        output = 'D'
    elif data >= 0.7:
        output = 'D-'

    return output

In [159]:
data = std_perf_df[" realestate"]
output = "A"

numeric_to_letter_grade(data)
   # return output.apply(numeric_to_letter_grade)

'D-'

In [160]:
def numeric_to_letter_grade(data):
    
    output = 'F'
    data = std_perf_df[" technology"]
    
    if data == 4.3:
        output = 'A+'
    elif data >= 4.0:
        data = 'A'
    elif data >= 3.7:
        output = 'A-'
    elif data >= 3.3:
        output = 'B+'
    elif data >= 3:
        output = 'B'
    elif data >= 2.7:
        output = 'B-'
    elif data >= 2.3:
        output = 'C+'
    elif data >= 2:
        output = 'C'
    elif data >= 1.7:
        output = 'C-'
    elif data >= 1.3:
        output = 'D+'
    elif data >= 1:
        output = 'D'
    elif data >= 0.7:
        output = 'D-'

    return output

In [161]:
data = std_perf_df[" technology"]
output = "A"

numeric_to_letter_grade(data)
   # return output.apply(numeric_to_letter_grade)

'F'

In [162]:
def numeric_to_letter_grade(data):
    
    output = 'F'
    data = std_perf_df[" utilities"]
    
    if data == 4.3:
        output = 'A+'
    elif data >= 4.0:
        data = 'A'
    elif data >= 3.7:
        output = 'A-'
    elif data >= 3.3:
        output = 'B+'
    elif data >= 3:
        output = 'B'
    elif data >= 2.7:
        output = 'B-'
    elif data >= 2.3:
        output = 'C+'
    elif data >= 2:
        output = 'C'
    elif data >= 1.7:
        output = 'C-'
    elif data >= 1.3:
        output = 'D+'
    elif data >= 1:
        output = 'D'
    elif data >= 0.7:
        output = 'D-'

    return output

In [163]:
data = std_perf_df[" utilities"]
output = "A"

numeric_to_letter_grade(data)
   # return output.apply(numeric_to_letter_grade)

'F'